### PR TITLE
Introduced template scope: wrap each template in IIFE

### LINKED ISSUE #75: Template Scope
Each template must be performed in its scope.

Need wrap each template in IIFE (Immediately-invoked function expression).

Actual only for `bh-bundle` tech.

### PR DESCRIPTION
**Pull request by blond**
Resolved #75

### CODE REVIEW

**Comment by tadatuta** [comment]
are you sure it shouldn't be optional?

**Comment by blond** [comment]
@tadatuta if someone really need, we can add option later.

**Comment by tadatuta** [comment]
shouldn't it be possible to switch them off to make result bundle smaller?

**Comment by blond** [comment]
@tadatuta I don't think it is so important. In any case, we can add an option later.

**Comment by blond** [comment]
@tadatuta create issue #80

**Pull request merged**
